---
- name: Install Docker on Ubuntu Server
  hosts: ubuntu
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install Docker dependencies
      apt:
        name: 
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Compose
      shell: >
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
        chmod +x /usr/local/bin/docker-compose

    - name: Docker sudo permissions
      shell: >
        sudo chmod 777 /var/run/docker.sock

    - name: Install Docker container module
      shell: >
        ansible-galaxy collection install community.docker

    - name: Install SonarQube container
      community.docker.docker_container:
        name: sonar
        image: sonarqube:lts-community
        state: started
        ports:
          - "9000:9000"