---
- name: Install Jenkins on Ubuntu Server
  hosts: ubuntu
  become: yes

  tasks:
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Instalar dependencias libc6-x32 y libc6-i386
      apt:
        name:
          - libc6-x32
          - libc6-i386
        state: present

    - name: Descargar e instalar JDK 17 desde Oracle
      get_url:
        url: "https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb"
        dest: "/tmp/jdk-17_linux-x64_bin.deb"

    - name: Instalar JDK 17 desde el paquete descargado
      apt:
        deb: "/tmp/jdk-17_linux-x64_bin.deb"
        state: present

    - name: Descargar la clave de Jenkins
      shell: >
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
                  /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Añadir el repositorio de Jenkins
      shell: >
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
                  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
                              /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Actualizar la lista de paquetes después de añadir el repositorio
      apt:
        update_cache: yes

    - name: Instalar Jenkins
      apt:
        name: jenkins
        state: present

    - name: Iniciar el servicio Jenkins
      systemd:
        name: jenkins
        state: started

    - name: Verificar el estado de Jenkins
      command: systemctl status jenkins
      register: result
      changed_when: false