---
- hosts: ubuntu
  become: yes
  tasks:
    - name: Actualizar los paquetes del sistema
      apt:
        update_cache: yes

    - name: Instalar curl
      apt:
        name: curl
        state: present

    - name: Descargar kubectl
      get_url:
        url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'

    - name: Instalar kubectl
      copy:
        src: "/tmp/kubectl"
        dest: "/usr/local/bin/kubectl"
        owner: root
        group: root
        mode: '0755'

    - name: Verificar la versión de kubectl
      command: kubectl version --client
      register: version
      changed_when: false

    - name: Mostrar la versión de kubectl
      debug:
        var: version.stdout_lines