---
- name: Install Trivy on Ubuntu Server
  hosts: ubuntu
  become: yes

  tasks:
    - name: Instalar paquetes necesarios
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
        state: present

    - name: Descargar y añadir la clave pública de Trivy
      get_url:
        url: "https://aquasecurity.github.io/trivy-repo/deb/public.key"
        dest: "/tmp/trivy-public.key"

    - name: Desarmar la clave
      command: 
        cmd: gpg --dearmor --output /tmp/trivy-public.gpg /tmp/trivy-public.key
      become: yes

    - name: Mover la clave a keyring
      copy: 
        src: /tmp/trivy-public.gpg
        dest: /usr/share/keyrings/trivy.gpg
        remote_src: yes
      become: yes

    - name: Obtener la versión de la distribución
      command: lsb_release -sc
      register: distro_version
      changed_when: false

    - name: Añadir el repositorio de Trivy
      lineinfile:
        path: "/etc/apt/sources.list.d/trivy.list"
        line: "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb {{ distro_version.stdout }} main"
        create: yes

    - name: Actualizar la lista de paquetes después de añadir el repositorio
      apt:
        update_cache: yes

    - name: Instalar Trivy
      apt:
        name: trivy
        state: present